env:
        global:
                # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
                #   via the "travis encrypt" command using the project repo's public key
                - secure: "Jw8Q8kFOfP4kiicGpZX496H0Hhi2+PzQ5wSpSJ/+e4rdQ/PnQuCvJfyAJ/k6+7BmgeS80T4sfK5xB5nX3yZG1FA4VE4kXuppJlVSwTZer0dlbbK3rvdSChBf5/Nnfjsj/Ch2SjjwhOt8zhjVutWuT2wz9RwOO39heQf3KFb4qbaVbnaBRTiGYJ+6D/28dX5foMehTohtcN1WKUZULum4cP8tqdn2+0cH+afwDwODap4v8brEW8HifS4QGDejAE7zR9fr3BaJl2m9s8art5lGzoK6Qaf2SS8WBW0MVzv2CP6zfsLUmPm3WijGUzAIPPi5GRFSy7O0GdkhHziMof1vyE3irXLSFlhg5g76lHEI2vpE6m+/PQ4I9jp7+oBT0N4SadgiXReXxewAZRrInCOstNN/mWIF0C0r1gWvPS3uM5u4PfGRa72GJ39SWmDvQqmOHOy15ZGA2eyw8piLAVkVJKvhufNfwEULITHE9xQXCV3e0YZrNIjMofuRszz7yLHEXlhwJxG++E4h0uCKnCqLTcLas8sBcRw98H/k9s8yZR3u9v0F0qqX/wus2TvfMjsfOqMm9MyqTXexpsMiODiN0a8zpdhufDlyxgr+2S96NlER7Iu0aRPBVgfDP2COPxmVW4ZwDpZYxK6iANeiYVuQGHccDHjZRyiSCG2c47EKV14="
                - COVERITY_SCAN_PROJECT_NAME="saprykin/plib"
                - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"
                - COVERITY_SCAN_NOTIFICATION_EMAIL="xelfium@gmail.com"
                - COVERITY_SCAN_BUILD_COMMAND="make"

language: cpp

os:
        - linux
        - osx

compiler:
        - gcc
        - clang

branches:
        only:
                - master
                - coverity_scan

before_install:
        - if ([[ "${TRAVIS_JOB_NUMBER##*.}" == "1" ]] || [[ "${TRAVIS_JOB_NUMBER##*.}" == "3" ]]) && [[ "${TRAVIS_BRANCH}" != "coverity_scan" ]]; then export USE_GCOV="1" ; fi
        - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get update -qq ; fi
        - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install libboost-test-dev ; fi
        - if [[ "${USE_GCOV}" == "1" ]] && [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install lcov ; fi
        - if [[ "${USE_GCOV}" == "1" ]] && [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew update ; brew install lcov ; fi


before_script:
        - mkdir ./plib-build
        - cd ./plib-build
        - if [[ "${USE_GCOV}" == "1" ]]; then cmake -DPLIB_COVERAGE=ON .. ; else cmake -DCMAKE_BUILD_TYPE=Release .. ; fi
        - if [[ "${TRAVIS_JOB_NUMBER##*.}" == "1" ]]; then curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | bash || true ; fi

script:
        - make
        - if [[ "${TRAVIS_BRANCH}" != "coverity_scan" ]]; then ctest -V ; fi

after_success:
        - if [[ "${USE_GCOV}" == "1" ]]; then lcov --directory . --capture --output-file coverage.info ; fi
        - if [[ "${USE_GCOV}" == "1" ]]; then bash <(curl -s https://codecov.io/bash) ; fi
